language: cpp

compiler: gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake sqlite3 qt4-dev-tools

before_script:
    - mkdir build
    - cd build
    - cmake ../XInputSimulator/

script: make
